### ISSUE TITLE
Extract metamask interaction methods from index.ts

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/dappeteer#17]
Maybe have `src/metamask` directory with every method in separate file?

**Comment by BeroBurny** [comment]
for now, is manageable probably when we bring versioning it will be useful (probably whit will be pointless as MetaMask updates automatically on all browsers)

**Comment by mpetrunic** [comment]
not everyone install metamask from chrome store^^

**Comment by mpetrunic** [comment]
but it's easier to read code if logic is clearly separated by files. I was scrolling and searching endlessly for methods 😄

**Comment by BeroBurny** [comment]
then we can do it, and we gonna support order versions or just new ones?

**Comment by mpetrunic** [comment]
let's just support new ones until we encounter something that forces us otherwise
