### ISSUE TITLE
dappeteer undefined

### ISSUE THREAD

**Issue by himat** [NodeFactoryIo/dappeteer#21]
Hi I had this import undefined issue on the original dappeteer, so then I found this fork but I'm still having the same issue.

I installed dappeteer and puppeteer with `yarn add @nodefactory/dappeteer` and `yarn add puppeteer` and `yarn add -D @types/puppeteer`.
I then proceeded to run this simple function, but it seems like the dappeteer import is undefined.

`TypeError: Cannot read property 'launch' of undefined`

My file: `minting.ts`
```
import puppeteer from "puppeteer";
import dappeteer from "dappeteer";

export async function run() {
  const browser = await dappeteer.launch(puppeteer);
  const metamask = await dappeteer.getMetamask(browser);

  await browser.close();
}
```

```
❯ yarn -v
1.22.4
❯ node -v
v12.13.0

```

Is there some kind of more information I can provide to help debug why this is?

**Comment by mhluska** [comment]
Did you resolve this?

**Comment by hugoobauer** [comment]
I have the same issue :

Node version : 16.13.1

```
  "dependencies": {
    "@chainsafe/dappeteer": "^2.4.0",
    "puppeteer": "^13.1.3",
    "typescript": "^4.5.5"
  },
  "devDependencies": {
    "@types/puppeteer": "^5.4.4"
  }
```

```
import puppeteer from "puppeteer";
import dappeteer from '@chainsafe/dappeteer';

(async () => {
    const browser = await dappeteer.launch(puppeteer, { metamaskVersion: 'v10.8.1' });
    const page = await browser.newPage();
    await page.goto('http://example.com/');
    await page.waitForTimeout(1000)
    await page.screenshot({ path: 'example.png' });

    await browser.close();
})();

```

**Comment by keithfrazier98** [comment]
@hugoobauer try this -> `import * as dappeteer from "@chainsafe/dappeteer";`

**Comment by tcitds1** [comment]
> @hugoobauer try this -> `import * as dappeteer from "@chainsafe/dappeteer";`

appreciate it. you are a genius.
