### ISSUE TITLE
addNetwork function doesn't work

### ISSUE THREAD

**Issue by pybfinger** [NodeFactoryIo/dappeteer#22]
Hi there,

Thanks for the fork. As you suggested, might be an alternative as the original repo doesn't seem to be maintained.

I tested and was able to open Metamask.

However, it seems the addNetwork() function doesn't work; it just timeouts:

`UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `.network-indicator` failed: timeout 30000ms exceeded`

**Comment by mpetrunic** [comment]
Hi there, sorry for late response, seems like we forgot to set notifications on the repo. We will take a look at this and report back.

**Comment by mpetrunic** [comment]
fixed in v2.0.1
